{% set name = "mrs_denoising_tools" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08e7e3ec7e49f3728a60a140d3235912e6f5c0ac2f1ad92a61b930d71c36def4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mrsi_denoise = mrs_denoising.mrsi_denoise:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - nibabel

test:
  requires:
    - python {{ python_min }}
  imports:
    - mrs_denoising
  commands:
    - mrsi_denoise --help


about:
  home: https://git.fmrib.ox.ac.uk/wclarke/low-rank-denoising-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Package for low-rank denoising of magnetic resonance spectroscopic imaging
  # The remaining entries in this section are optional, but recommended.
  description: |
    mrs-denoising-tools is a collection of low-rank denoising functions for
    magnetic resonance spectroscopic imaging.
    It is pure Python code with simple dependencies.
  dev_url: https://git.fmrib.ox.ac.uk/wclarke/low-rank-denoising-tools

extra:
  recipe-maintainers:
    - wtclarke
